### ISSUE TITLE
Error duing compilation of DUtils

### ISSUE THREAD

**Issue by iArti** [ResurrectionRemix/external_DUtils#1]
I'm building RR 5.7.4 (MM) for my vivalto3gvn (SGA 4 Lite)
But DUtils can not be compiled because of these errors
`ERROR: /home/arti/RR/external/DUtils/src/com/android/internal/utils/du/DUActionUtils.java:112: The method navigationBarCanMove() is undefined for the type IWindowManager
ERROR: /home/arti/RR/external/DUtils/src/com/android/internal/utils/du/ActionHandler.java:366: The method showCustomIntentAfterKeyguard(Intent) is undefined for the type IStatusBarService
ERROR: /home/arti/RR/external/DUtils/src/com/android/internal/utils/du/ActionConstants.java:396: FLING_GESTURE_ACTIONS cannot be resolved or is not a field
`

**Comment by iArti** [comment]
Using OpenJDK-7 on Ubuntu 16.04 x64

**Comment by varund7726** [comment]
Probably an issue In the mm source.its deprecated now .sorry
